# T-Pot (HP)
# For docker-compose ...
version: '2.2'

networks:
  cowrie_local:
  dionaea_local:
  elasticpot_local:
  glastopf_local:
  mailoney_local:
  rdpy_local:
  vnclowpot_local:
  conpot_local:
  emobility_local:

services:

# Cowrie service
  cowrie:
    container_name: cowrie
    restart: always
    networks:
     - cowrie_local
    cap_add:
     - NET_BIND_SERVICE
    ports:
     - "22:2222"
     - "23:2223"
    image: "loanbo/cowrie"
    volumes:
     - /data/cowrie/downloads:/home/cowrie/cowrie/dl
     - /data/cowrie/keys:/home/cowrie/cowrie/etc
     - /data/cowrie/log:/home/cowrie/cowrie/log
     - /data/cowrie/log/tty:/home/cowrie/cowrie/log/tty
     - /etc/localtime:/etc/localtime
     
# Dionaea service
  dionaea:
    container_name: dionaea
    stdin_open: true
    restart: always
    networks:
     - dionaea_local
    cap_add:
     - NET_BIND_SERVICE
    ports:
     - "20:20"
     - "21:21"
     - "42:42"
     - "69:69/udp"
     - "8081:80"
     - "135:135"
     - "443:443"
     - "445:445"
     - "1433:1433"
     - "1723:1723"
     - "1883:1883"
     - "3306:3306"
     - "5060:5060"
     - "5060:5060/udp"
     - "5061:5061"
     - "27017:27017"
    image: "loanbo/dionaea"
    volumes:
     - /data/dionaea/roots/ftp:/opt/dionaea/var/dionaea/roots/ftp
     - /data/dionaea/roots/tftp:/opt/dionaea/var/dionaea/roots/tftp
     - /data/dionaea/roots/www:/opt/dionaea/var/dionaea/roots/www
     - /data/dionaea/roots/upnp:/opt/dionaea/var/dionaea/roots/upnp
     - /data/dionaea:/opt/dionaea/var/dionaea
     - /data/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
     - /data/dionaea/log:/opt/dionaea/var/log
     - /data/dionaea/rtp:/opt/dionaea/var/dionaea/rtp
     - /etc/localtime:/etc/localtime

# Elasticpot service
  elasticpot:
    container_name: elasticpot
    restart: always
    networks:
     - elasticpot_local
    ports:
     - "9200:9200"
    image: "dtagdevsec/elasticpot:1710"
    volumes:
     - /data/elasticpot/log:/opt/ElasticpotPY/log
     - /etc/localtime:/etc/localtime


# Glastopf service
  glastopf:
    container_name: glastopf
    restart: always
    networks:
     - glastopf_local
    ports:
     - "80:80"
    image: "dtagdevsec/glastopf:1710"
    volumes:
     - /data/glastopf/db:/opt/glastopf/db
     - /data/glastopf/log:/opt/glastopf/log
     - /etc/localtime:/etc/localtime

# Honeytrap service
  honeytrap:
    container_name: honeytrap
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
    image: "dtagdevsec/honeytrap:1710"
    volumes:
     - /data/honeytrap/attacks:/opt/honeytrap/var/attacks
     - /data/honeytrap/downloads:/opt/honeytrap/var/downloads
     - /data/honeytrap/log:/opt/honeytrap/var/log
     - /etc/localtime:/etc/localtime

# Mailoney service
  mailoney:
    container_name: mailoney
    restart: always
    networks:
     - mailoney_local
    ports:
     - "25:2525"
    image: "dtagdevsec/mailoney:1710"
    volumes:
     - /data/mailoney/log:/opt/mailoney/logs
     - /etc/localtime:/etc/localtime

# Rdpy service
  rdpy:
    container_name: rdpy
    restart: always
    networks:
     - rdpy_local
    ports:
     - "3389:3389"
    image: "dtagdevsec/rdpy:1710"
    volumes:
     - /data/rdpy/log:/var/log/rdpy
     - /etc/localtime:/etc/localtime

# Vnclowpot service
  vnclowpot:
    container_name: vnclowpot
    restart: always
    networks:
     - vnclowpot_local
    ports:
     - "5900:5900"
    image: "dtagdevsec/vnclowpot:1710"
    volumes:
     - /data/vnclowpot/log:/var/log/vnclowpot
     - /etc/localtime:/etc/localtime
 
 # Conpot service
  conpot:
    container_name: conpot
    restart: always
    networks:
     - conpot_local
    ports:
     - "1025:1025"
     - "50100:50100"
    image: "dtagdevsec/conpot:1710"
    volumes:
     - /data/conpot/log:/var/log/conpot
     - /etc/localtime:/etc/localtime
  
 # Emobility service
  emobility:
    container_name: emobility
    restart: always
    networks:
     - emobility_local
    cap_add:
     - NET_ADMIN
    ports:
     - "8080:8080"
    image: "dtagdevsec/emobility:1710"
    volumes:
     - /data/emobility:/data/eMobility
     - /data/ews:/data/ews
     - /etc/localtime:/etc/localtime

# Netdata service
  netdata:
    container_name: netdata
    restart: always
    network_mode: "host"
    cap_add:
     - SYS_PTRACE
    ports:
     - "19999:19999"
    security_opt:
     - apparmor=unconfined
    image: "loanbo/netdata"
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
     - /var/run/docker.sock:/var/run/docker.sock
     - /etc/localtime:/etc/localtime
